// Build site/about.js — GPT-5.5-written info blurbs for each species (name origin, family &
// relatives, a fun fact). English source; translated later by build_i18n.js.
//   OPENAI_API_KEY=… node scripts/build_about.js

const fs = require("fs");
const path = require("path");

function loadSpecies() {
  const g = {};
  new Function("window", fs.readFileSync(path.join(__dirname, "..", "site", "species.js"), "utf8"))(g);
  return g.NYCTREES_SPECIES || [];
}

async function main() {
  const all = loadSpecies().map((s) => ({ id: s.id, common: s.common, scientific: s.scientific, family: s.family }));
  const dst = path.join(__dirname, "..", "site", "about.js");
  // Merge into existing blurbs so a re-run never clobbers hand-edits or costs a full regen.
  const about = {};
  if (fs.existsSync(dst)) { const g = {}; new Function("window", fs.readFileSync(dst, "utf8"))(g); Object.assign(about, g.NYCTREES_ABOUT || {}); }
  // Default: only generate species missing a blurb. ABOUT_ONLY=id,id forces a subset.
  const only = process.env.ABOUT_ONLY ? new Set(process.env.ABOUT_ONLY.split(",")) : null;
  const todo = all.filter((s) => (only ? only.has(s.id) : !about[s.id]));
  if (!todo.length) { console.log("about.js: nothing to generate"); return; }
  const prompt =
    `You are a botanist writing short, factual info cards for a New York City street-tree learning app.\n` +
    `For EACH tree below, return concise, accurate info. Return ONLY a JSON object keyed by the tree "id", ` +
    `each value an object with exactly these fields:\n` +
    `  "name"      — how it got its common and/or scientific name (etymology/origin), 1–2 sentences.\n` +
    `  "relatives" — its plant family and a notable close relative or two, 1 sentence.\n` +
    `  "fact"      — one genuinely interesting fun fact, cultural note, or traditional use, 1 sentence.\n` +
    `Be factual and engaging, no fluff, no marketing. Do not invent etymologies — if unsure, describe what is known.\n` +
    `Trees:\n${JSON.stringify(todo, null, 0)}`;
  // Provider fallback: ABOUT_PROVIDER=gemini routes to Gemini when the OpenAI quota is exhausted.
  const gemini = process.env.ABOUT_PROVIDER === "gemini";
  const url = gemini
    ? "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions"
    : "https://api.openai.com/v1/chat/completions";
  const key = gemini ? process.env.GEMINI_API_KEY : process.env.OPENAI_API_KEY;
  const body = gemini
    ? { model: "gemini-2.5-pro", max_tokens: 20000, response_format: { type: "json_object" }, messages: [{ role: "user", content: prompt }] }
    : { model: "gpt-5.5", reasoning_effort: "medium", max_completion_tokens: 20000, response_format: { type: "json_object" }, messages: [{ role: "user", content: prompt }] };
  const r = await fetch(url, {
    method: "POST",
    headers: { Authorization: "Bearer " + key, "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  const j = await r.json();
  if (!j.choices) throw new Error("no choices: " + JSON.stringify(j).slice(0, 300));
  Object.assign(about, JSON.parse(j.choices[0].message.content));
  fs.writeFileSync(dst, "// AUTO-GENERATED by scripts/build_about.js (GPT-5.5). Hand-edits welcome.\n" +
    "window.NYCTREES_ABOUT = " + JSON.stringify(about, null, 1) + ";\n");
  console.log(`wrote ${dst} (${Object.keys(about).length} species; generated ${todo.length})`);
}
main();
